{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-12-22 09:59:54.267134: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading checkpoint checkpoint/steam/model-2\n",
      "INFO:tensorflow:Restoring parameters from checkpoint/steam/model-2\n",
      "Loading dataset...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1/1 [00:00<00:00, 1447.31it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dataset has 2195 tokens\n",
      "Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[3 | 18.98] loss=2.69 avg=2.69\n",
      "[4 | 40.25] loss=2.38 avg=2.54\n",
      "[5 | 60.33] loss=2.05 avg=2.37\n",
      "[6 | 79.96] loss=1.70 avg=2.20\n",
      "[7 | 100.06] loss=1.44 avg=2.04\n",
      "[8 | 119.76] loss=1.35 avg=1.93\n",
      "interrupted\n",
      "Saving checkpoint/steam/model-8\n"
     ]
    }
   ],
   "source": [
    "import gpt_2_simple as gpt2\n",
    "\n",
    "session =gpt2.start_tf_sess()\n",
    "gpt2.finetune(\n",
    "    session,\"Steam_questions.txt\", model_name=\"124M\", steps= 20, run_name= 'steam'\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "gpt2.generate(session, prefix ='How does this impact my high school graduation requirements?')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "gpt2.generate(session, prefix='Explain the smaller work-based learning opportunities I can get involved with.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-12-20 09:14:43.501338: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at resource_variable_ops.cc:721 : NOT_FOUND: Container localhost does not exist. (Could not find resource: localhost/model/wte)\n",
      "2023-12-20 09:14:43.501359: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at resource_variable_ops.cc:721 : NOT_FOUND: Container localhost does not exist. (Could not find resource: localhost/model/wpe)\n",
      "2023-12-20 09:14:43.501744: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at resource_variable_ops.cc:721 : NOT_FOUND: Container localhost does not exist. (Could not find resource: localhost/model/wte)\n"
     ]
    },
    {
     "ename": "FailedPreconditionError",
     "evalue": "Graph execution error:\n\nDetected at node 'sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp' defined at (most recent call last):\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 86, in _run_code\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel_launcher.py\", line 17, in <module>\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/traitlets/config/application.py\", line 1053, in launch_instance\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelapp.py\", line 736, in start\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tornado/platform/asyncio.py\", line 195, in start\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py\", line 1906, in _run_once\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py\", line 80, in _run\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n    File \"/var/folders/xs/ncmfvgpd1qzc07xxb9p5bkmw0000gq/T/ipykernel_20176/1936187500.py\", line 1, in <module>\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/gpt_2.py\", line 462, in generate\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/sample.py\", line 67, in sample_sequence\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/sample.py\", line 51, in step\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 203, in model\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 158, in block\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 148, in mlp\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 85, in conv1d\nNode: 'sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp'\nCould not find variable model/h5/mlp/c_fc/b. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Container localhost does not exist. (Could not find resource: localhost/model/h5/mlp/c_fc/b)\n\t [[{{node sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp}}]]\n\nOriginal stack trace for 'sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp':\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 86, in _run_code\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel_launcher.py\", line 17, in <module>\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/traitlets/config/application.py\", line 1053, in launch_instance\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelapp.py\", line 736, in start\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tornado/platform/asyncio.py\", line 195, in start\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py\", line 1906, in _run_once\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py\", line 80, in _run\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n  File \"/var/folders/xs/ncmfvgpd1qzc07xxb9p5bkmw0000gq/T/ipykernel_20176/1936187500.py\", line 1, in <module>\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/gpt_2.py\", line 462, in generate\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/sample.py\", line 67, in sample_sequence\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/sample.py\", line 51, in step\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 203, in model\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 158, in block\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 148, in mlp\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 85, in conv1d\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/math_ops.py\", line 1478, in binary_op_wrapper\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/util/dispatch.py\", line 1260, in op_dispatch_handler\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/math_ops.py\", line 1867, in _add_dispatch\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/ops.py\", line 696, in convert_to_tensor\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/tensor_conversion_registry.py\", line 217, in convert\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 2340, in _dense_var_to_tensor\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 1582, in _dense_var_to_tensor\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 634, in value\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 818, in _read_variable_op\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 808, in read_and_set_handle\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py\", line 548, in read_variable_op\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/op_def_library.py\", line 796, in _apply_op_helper\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/ops.py\", line 2652, in _create_op_internal\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/ops.py\", line 1160, in from_node_def\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFailedPreconditionError\u001b[0m                   Traceback (most recent call last)",
      "File \u001b[0;32m~/Library/Python/3.10/lib/python/site-packages/tensorflow/python/client/session.py:1402\u001b[0m, in \u001b[0;36mBaseSession._do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n\u001b[1;32m   1401\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> 1402\u001b[0m   \u001b[39mreturn\u001b[39;00m fn(\u001b[39m*\u001b[39;49margs)\n\u001b[1;32m   1403\u001b[0m \u001b[39mexcept\u001b[39;00m errors\u001b[39m.\u001b[39mOpError \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/Library/Python/3.10/lib/python/site-packages/tensorflow/python/client/session.py:1385\u001b[0m, in \u001b[0;36mBaseSession._do_run.<locals>._run_fn\u001b[0;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[1;32m   1384\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_extend_graph()\n\u001b[0;32m-> 1385\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_call_tf_sessionrun(options, feed_dict, fetch_list,\n\u001b[1;32m   1386\u001b[0m                                 target_list, run_metadata)\n",
      "File \u001b[0;32m~/Library/Python/3.10/lib/python/site-packages/tensorflow/python/client/session.py:1478\u001b[0m, in \u001b[0;36mBaseSession._call_tf_sessionrun\u001b[0;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[1;32m   1476\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_call_tf_sessionrun\u001b[39m(\u001b[39mself\u001b[39m, options, feed_dict, fetch_list, target_list,\n\u001b[1;32m   1477\u001b[0m                         run_metadata):\n\u001b[0;32m-> 1478\u001b[0m   \u001b[39mreturn\u001b[39;00m tf_session\u001b[39m.\u001b[39;49mTF_SessionRun_wrapper(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_session, options, feed_dict,\n\u001b[1;32m   1479\u001b[0m                                           fetch_list, target_list,\n\u001b[1;32m   1480\u001b[0m                                           run_metadata)\n",
      "\u001b[0;31mFailedPreconditionError\u001b[0m: Could not find variable model/h5/mlp/c_fc/b. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Container localhost does not exist. (Could not find resource: localhost/model/h5/mlp/c_fc/b)\n\t [[{{node sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp}}]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mFailedPreconditionError\u001b[0m                   Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m gpt2\u001b[39m.\u001b[39;49mgenerate(session, prefix \u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mHow/When do I decide which CTE pathway I want to study? Can I choose more than one?\u001b[39;49m\u001b[39m'\u001b[39;49m)\n",
      "File \u001b[0;32m~/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/gpt_2.py:479\u001b[0m, in \u001b[0;36mgenerate\u001b[0;34m(sess, run_name, checkpoint_dir, model_name, model_dir, sample_dir, return_as_list, truncate, destination_path, sample_delim, prefix, seed, nsamples, batch_size, length, temperature, top_k, top_p, include_prefix)\u001b[0m\n\u001b[1;32m    477\u001b[0m     out \u001b[39m=\u001b[39m sess\u001b[39m.\u001b[39mrun(output)\n\u001b[1;32m    478\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m--> 479\u001b[0m     out \u001b[39m=\u001b[39m sess\u001b[39m.\u001b[39;49mrun(output, feed_dict\u001b[39m=\u001b[39;49m{\n\u001b[1;32m    480\u001b[0m             context: batch_size \u001b[39m*\u001b[39;49m [context_tokens]\n\u001b[1;32m    481\u001b[0m         })\n\u001b[1;32m    482\u001b[0m \u001b[39mfor\u001b[39;00m i \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(batch_size):\n\u001b[1;32m    483\u001b[0m     generated \u001b[39m+\u001b[39m\u001b[39m=\u001b[39m \u001b[39m1\u001b[39m\n",
      "File \u001b[0;32m~/Library/Python/3.10/lib/python/site-packages/tensorflow/python/client/session.py:972\u001b[0m, in \u001b[0;36mBaseSession.run\u001b[0;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m    969\u001b[0m run_metadata_ptr \u001b[39m=\u001b[39m tf_session\u001b[39m.\u001b[39mTF_NewBuffer() \u001b[39mif\u001b[39;00m run_metadata \u001b[39melse\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m    971\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 972\u001b[0m   result \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_run(\u001b[39mNone\u001b[39;49;00m, fetches, feed_dict, options_ptr,\n\u001b[1;32m    973\u001b[0m                      run_metadata_ptr)\n\u001b[1;32m    974\u001b[0m   \u001b[39mif\u001b[39;00m run_metadata:\n\u001b[1;32m    975\u001b[0m     proto_data \u001b[39m=\u001b[39m tf_session\u001b[39m.\u001b[39mTF_GetBuffer(run_metadata_ptr)\n",
      "File \u001b[0;32m~/Library/Python/3.10/lib/python/site-packages/tensorflow/python/client/session.py:1215\u001b[0m, in \u001b[0;36mBaseSession._run\u001b[0;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1212\u001b[0m \u001b[39m# We only want to really perform the run if fetches or targets are provided,\u001b[39;00m\n\u001b[1;32m   1213\u001b[0m \u001b[39m# or if the call is a partial run that specifies feeds.\u001b[39;00m\n\u001b[1;32m   1214\u001b[0m \u001b[39mif\u001b[39;00m final_fetches \u001b[39mor\u001b[39;00m final_targets \u001b[39mor\u001b[39;00m (handle \u001b[39mand\u001b[39;00m feed_dict_tensor):\n\u001b[0;32m-> 1215\u001b[0m   results \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_do_run(handle, final_targets, final_fetches,\n\u001b[1;32m   1216\u001b[0m                          feed_dict_tensor, options, run_metadata)\n\u001b[1;32m   1217\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   1218\u001b[0m   results \u001b[39m=\u001b[39m []\n",
      "File \u001b[0;32m~/Library/Python/3.10/lib/python/site-packages/tensorflow/python/client/session.py:1395\u001b[0m, in \u001b[0;36mBaseSession._do_run\u001b[0;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1392\u001b[0m   \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_call_tf_sessionprun(handle, feed_dict, fetch_list)\n\u001b[1;32m   1394\u001b[0m \u001b[39mif\u001b[39;00m handle \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m-> 1395\u001b[0m   \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[1;32m   1396\u001b[0m                        run_metadata)\n\u001b[1;32m   1397\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   1398\u001b[0m   \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_do_call(_prun_fn, handle, feeds, fetches)\n",
      "File \u001b[0;32m~/Library/Python/3.10/lib/python/site-packages/tensorflow/python/client/session.py:1421\u001b[0m, in \u001b[0;36mBaseSession._do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n\u001b[1;32m   1416\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39m'\u001b[39m\u001b[39monly supports NHWC tensor format\u001b[39m\u001b[39m'\u001b[39m \u001b[39min\u001b[39;00m message:\n\u001b[1;32m   1417\u001b[0m   message \u001b[39m+\u001b[39m\u001b[39m=\u001b[39m (\u001b[39m'\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39mA possible workaround: Try disabling Grappler optimizer\u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m   1418\u001b[0m               \u001b[39m'\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39mby modifying the config for creating the session eg.\u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m   1419\u001b[0m               \u001b[39m'\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39msession_config.graph_options.rewrite_options.\u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m   1420\u001b[0m               \u001b[39m'\u001b[39m\u001b[39mdisable_meta_optimizer = True\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m-> 1421\u001b[0m \u001b[39mraise\u001b[39;00m \u001b[39mtype\u001b[39m(e)(node_def, op, message)\n",
      "\u001b[0;31mFailedPreconditionError\u001b[0m: Graph execution error:\n\nDetected at node 'sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp' defined at (most recent call last):\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 86, in _run_code\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel_launcher.py\", line 17, in <module>\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/traitlets/config/application.py\", line 1053, in launch_instance\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelapp.py\", line 736, in start\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tornado/platform/asyncio.py\", line 195, in start\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py\", line 1906, in _run_once\n    File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py\", line 80, in _run\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n    File \"/var/folders/xs/ncmfvgpd1qzc07xxb9p5bkmw0000gq/T/ipykernel_20176/1936187500.py\", line 1, in <module>\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/gpt_2.py\", line 462, in generate\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/sample.py\", line 67, in sample_sequence\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/sample.py\", line 51, in step\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 203, in model\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 158, in block\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 148, in mlp\n    File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 85, in conv1d\nNode: 'sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp'\nCould not find variable model/h5/mlp/c_fc/b. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Container localhost does not exist. (Could not find resource: localhost/model/h5/mlp/c_fc/b)\n\t [[{{node sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp}}]]\n\nOriginal stack trace for 'sample_sequence_1/model/h5/mlp/c_fc/add/ReadVariableOp':\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 86, in _run_code\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel_launcher.py\", line 17, in <module>\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/traitlets/config/application.py\", line 1053, in launch_instance\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelapp.py\", line 736, in start\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tornado/platform/asyncio.py\", line 195, in start\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py\", line 1906, in _run_once\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py\", line 80, in _run\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n  File \"/var/folders/xs/ncmfvgpd1qzc07xxb9p5bkmw0000gq/T/ipykernel_20176/1936187500.py\", line 1, in <module>\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/gpt_2.py\", line 462, in generate\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/sample.py\", line 67, in sample_sequence\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/sample.py\", line 51, in step\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 203, in model\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 158, in block\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 148, in mlp\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/gpt_2_simple/src/model.py\", line 85, in conv1d\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/math_ops.py\", line 1478, in binary_op_wrapper\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/util/dispatch.py\", line 1260, in op_dispatch_handler\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/math_ops.py\", line 1867, in _add_dispatch\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/ops.py\", line 696, in convert_to_tensor\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/tensor_conversion_registry.py\", line 217, in convert\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 2340, in _dense_var_to_tensor\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 1582, in _dense_var_to_tensor\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 634, in value\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 818, in _read_variable_op\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py\", line 808, in read_and_set_handle\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py\", line 548, in read_variable_op\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/op_def_library.py\", line 796, in _apply_op_helper\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/ops.py\", line 2652, in _create_op_internal\n  File \"/Users/CircuitBreakers/Library/Python/3.10/lib/python/site-packages/tensorflow/python/framework/ops.py\", line 1160, in from_node_def\n"
     ]
    }
   ],
   "source": [
    "gpt2.generate(session, prefix ='How/When do I decide which CTE pathway I want to study? Can I choose more than one?')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
